package app.nexstream.player.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily

/**
 * Hardcoded defaults — used when the API is unreachable AND the cached theme file
 * hasn't been written yet (i.e. very first launch with no connectivity).
 * Values mirror theme-dark-default.json / theme-light-default.json exactly.
 */
object ThemeDefaults {

    val dark: NexStreamTheme = NexStreamTheme(
        isDark   = true,
        version  = 1,
        identity = NexStreamIdentity(
            appName   = "nexStream",
            logoMode  = LogoMode.TEXT,
            fontFamily = FontFamily.Default, // replaced with Exo2 by ThemeManager once loaded
        ),
        sidebar = NexStreamSidebarColors(
            background            = Color(0xFF0D0D1A),
            railBackground        = Color(0xFF0A0A14),
            railItemActiveBg      = Color(0xFF1E2A4A),
            railItemFocusedBg     = Color(0xFF16213A),
            railIcon              = Color(0xFF5A7AAF),
            railIconActive        = Color(0xFF7EB3FF),
            panelBackground       = Color(0xFF0F0F1E),
            categorySelectedBg    = Color(0xFF1A2A5A),
            categoryFocusedBg     = Color(0xFF141E3A),
            categoryText          = Color(0xFF6A85B5),
            categoryTextSelected  = Color(0xFFA8C4F0),
            categoryTextFocused   = Color(0xFFC8D8FF),
            divider               = Color(0xFF1E1E35),
            accountBarBg          = Color(0xFF080810),
            accountBarText        = Color(0xFF8AAADD),
            accountBarTextSecondary = Color(0xFF5A7AAF),
        ),
        epg = NexStreamEpgColors(
            background              = Color(0xFF0A0A14),
            headerBackground        = Color(0xFF0D0D1A),
            headerTimeText          = Color(0xFF5A7AAF),
            headerDayText           = Color(0xFF7EB3FF),
            headerDivider           = Color(0xFF1A1A35),
            channelColumnBg         = Color(0xFF0D0D1A),
            channelNameText         = Color(0xFFA8C4F0),
            channelDivider          = Color(0xFF1A1A35),
            rowFocusedTint          = Color(0xFF12183A),
            programCellBg           = Color(0xFF13132A),
            programCellNowBg        = Color(0xFF161A35),
            programCellPlaceholderBg= Color(0xFF0D0D1A),
            programCellFocusedBg    = Color(0xFF1E2E6A),
            programCellFocusedBorder= Color(0xFF5A8AEF),
            programText             = Color(0xFF6A85B5),
            programTextNow          = Color(0xFF8AAAE0),
            programTextFocused      = Color(0xFFC8D8FF),
            programTextPlaceholder  = Color(0xFF3A4A6A),
            nowLine                 = Color(0xFFD05050),
            divider                 = Color(0xFF1A1A35),
            badgeCatchupBg          = Color(0xFF1A3A5A),
            badgeCatchupText        = Color(0xFF5AAAF0),
            badgeReminderBg         = Color(0xFF3A2A0A),
            badgeReminderText       = Color(0xFFF0A030),
        ),
        player = NexStreamPlayerColors(
            controlsBg       = Color(0xCC000000),
            progressPlayed   = Color(0xFF5A8AEF),
            progressBuffered = Color(0xFF2A3A6A),
            progressBg       = Color(0xFF1A1A35),
            textPrimary      = Color(0xFFE8F0FF),
            textSecondary    = Color(0xFF8AAAE0),
        ),
        global = NexStreamGlobalColors(
            primary            = Color(0xFF5A8AEF),
            primaryContainer   = Color(0xFF1E2E6A),
            onPrimary          = Color(0xFFE8F0FF),
            onPrimaryContainer = Color(0xFFC8D8FF),
            surface            = Color(0xFF0D0D1A),
            surfaceVariant     = Color(0xFF13132A),
            onSurface          = Color(0xFFC8D8FF),
            onSurfaceVariant   = Color(0xFF8AAAE0),
            outline            = Color(0xFF2A3A6A),
            error              = Color(0xFFD05050),
        ),
    )

    val light: NexStreamTheme = NexStreamTheme(
        isDark   = false,
        version  = 1,
        identity = NexStreamIdentity(
            appName   = "nexStream",
            logoMode  = LogoMode.TEXT,
            fontFamily = FontFamily.Default,
        ),
        sidebar = NexStreamSidebarColors(
            background            = Color(0xFFF0F2F8),
            railBackground        = Color(0xFFE4E8F4),
            railItemActiveBg      = Color(0xFFC8D4F0),
            railItemFocusedBg     = Color(0xFFD4DCF4),
            railIcon              = Color(0xFF4A6AAF),
            railIconActive        = Color(0xFF2A4A9F),
            panelBackground       = Color(0xFFE8EDF8),
            categorySelectedBg    = Color(0xFFC0CFF0),
            categoryFocusedBg     = Color(0xFFCCD8F4),
            categoryText          = Color(0xFF4A6AAF),
            categoryTextSelected  = Color(0xFF1A3A8F),
            categoryTextFocused   = Color(0xFF0A2A7F),
            divider               = Color(0xFFC8D4EC),
            accountBarBg          = Color(0xFFD8E2F4),
            accountBarText        = Color(0xFF1A3A8F),
            accountBarTextSecondary = Color(0xFF4A6AAF),
        ),
        epg = NexStreamEpgColors(
            background              = Color(0xFFF4F6FC),
            headerBackground        = Color(0xFFE8EDF8),
            headerTimeText          = Color(0xFF4A6AAF),
            headerDayText           = Color(0xFF2A4A9F),
            headerDivider           = Color(0xFFC8D4EC),
            channelColumnBg         = Color(0xFFEDF0FA),
            channelNameText         = Color(0xFF1A3A8F),
            channelDivider          = Color(0xFFC8D4EC),
            rowFocusedTint          = Color(0xFFDCE8FF),
            programCellBg           = Color(0xFFFFFFFF),
            programCellNowBg        = Color(0xFFF0F5FF),
            programCellPlaceholderBg= Color(0xFFF0F2FA),
            programCellFocusedBg    = Color(0xFFC8D8FF),
            programCellFocusedBorder= Color(0xFF3A6ADF),
            programText             = Color(0xFF4A6AAF),
            programTextNow          = Color(0xFF2A4A9F),
            programTextFocused      = Color(0xFF0A2A7F),
            programTextPlaceholder  = Color(0xFF9AAAD0),
            nowLine                 = Color(0xFFD04040),
            divider                 = Color(0xFFC8D4EC),
            badgeCatchupBg          = Color(0xFFC8E0F8),
            badgeCatchupText        = Color(0xFF1A5AAF),
            badgeReminderBg         = Color(0xFFFFF0C8),
            badgeReminderText       = Color(0xFF8A5000),
        ),
        player = NexStreamPlayerColors(
            controlsBg       = Color(0xCC000000),
            progressPlayed   = Color(0xFF3A6ADF),
            progressBuffered = Color(0xFFC8D8FF),
            progressBg       = Color(0xFFE0E8FF),
            textPrimary      = Color(0xFF0A1A4F),
            textSecondary    = Color(0xFF3A5A9F),
        ),
        global = NexStreamGlobalColors(
            primary            = Color(0xFF3A6ADF),
            primaryContainer   = Color(0xFFC8D8FF),
            onPrimary          = Color(0xFFFFFFFF),
            onPrimaryContainer = Color(0xFF0A2A7F),
            surface            = Color(0xFFF4F6FC),
            surfaceVariant     = Color(0xFFE8EDF8),
            onSurface          = Color(0xFF0A1A4F),
            onSurfaceVariant   = Color(0xFF3A5A9F),
            outline            = Color(0xFFC8D4EC),
            error              = Color(0xFFD04040),
        ),
    )
}